import type { Incident, Evidence, DashboardMetrics } from './types';

// Mock evidence data
const mockEvidence: Record<string, Evidence> = {
  kb_vpn: {
    id: 'kb_vpn',
    type: 'knowledge_base',
    title: 'VPN Token Expiration Issues',
    content: 'When VPN tokens expire, users cannot authenticate. Common solution: request new token or use token reset procedure.',
    relevance: 95,
    source: 'KB Article #2341',
  },
  ticket_vpn: {
    id: 'ticket_vpn',
    type: 'ticket',
    title: 'Similar VPN Issue - User john.doe',
    content: 'Ticket #5432: User reported identical symptoms. Resolved by VPN token reset on 2026-09-28.',
    relevance: 88,
    source: 'Ticket #5432',
  },
  status_vpn: {
    id: 'status_vpn',
    type: 'system_status',
    title: 'VPN Service Status',
    content: 'VPN authentication service: OPERATIONAL. No current incidents.',
    relevance: 72,
    source: 'System Status Dashboard',
  },
  proc_vpn: {
    id: 'proc_vpn',
    type: 'procedure',
    title: 'VPN Token Reset Procedure',
    content: '1. Navigate to VPN admin console. 2. Find user account. 3. Click "Reset Token". 4. User receives new token via email. 5. Verify login works.',
    relevance: 100,
    source: 'IT Procedures',
  },
};

// Mock incidents
export const mockIncidents: Incident[] = [
  {
    id: 'INC-001',
    title: 'Cannot connect to VPN',
    description: 'User unable to authenticate to corporate VPN. Getting "invalid token" error.',
    status: 'resolved',
    createdAt: new Date(Date.now() - 15 * 60000),
    updatedAt: new Date(Date.now() - 2 * 60000),
    priority: 'high',
    category: 'VPN',
    events: [
      {
        id: 'evt-1',
        timestamp: new Date(Date.now() - 15 * 60000),
        agent: 'triage',
        status: 'completed',
        message: 'Issue classified as VPN authentication problem. Priority: HIGH.',
      },
      {
        id: 'evt-2',
        timestamp: new Date(Date.now() - 13 * 60000),
        agent: 'investigation',
        status: 'completed',
        message: 'Searched knowledge base, previous tickets, system status, and procedures.',
        evidence: [mockEvidence.kb_vpn, mockEvidence.ticket_vpn, mockEvidence.status_vpn, mockEvidence.proc_vpn],
      },
      {
        id: 'evt-3',
        timestamp: new Date(Date.now() - 11 * 60000),
        agent: 'diagnosis',
        status: 'completed',
        message: 'Root cause identified: VPN token has expired.',
        diagnosis: {
          likelyCause: 'User VPN token has expired and requires renewal',
          confidence: 96,
          supportingEvidence: [mockEvidence.kb_vpn, mockEvidence.ticket_vpn],
          uncertainty: 'Small chance of network connectivity issue, but evidence strongly suggests token expiration.',
        },
      },
      {
        id: 'evt-4',
        timestamp: new Date(Date.now() - 9 * 60000),
        agent: 'action_planner',
        status: 'completed',
        message: 'Selected action: Reset VPN token.',
        action: {
          id: 'act-1',
          tool: 'reset_vpn_token',
          description: 'Reset user VPN token and send new credentials via email',
          riskLevel: 'low',
          requiresApproval: false,
          linkedEvidence: [mockEvidence.proc_vpn, mockEvidence.kb_vpn],
          reasoning: 'Low-risk operation supported by KB article and successful precedent ticket.',
        },
      },
      {
        id: 'evt-5',
        timestamp: new Date(Date.now() - 7 * 60000),
        agent: 'verification',
        status: 'completed',
        message: 'Action executed: VPN token reset completed.',
      },
      {
        id: 'evt-6',
        timestamp: new Date(Date.now() - 5 * 60000),
        agent: 'verification',
        status: 'completed',
        message: 'Verification: User successfully authenticated to VPN. Issue RESOLVED.',
      },
    ],
    evidence: [mockEvidence.kb_vpn, mockEvidence.ticket_vpn, mockEvidence.status_vpn, mockEvidence.proc_vpn],
    diagnosis: {
      likelyCause: 'VPN token expiration',
      confidence: 96,
      supportingEvidence: [mockEvidence.kb_vpn, mockEvidence.ticket_vpn],
    },
    approvalRequired: false,
    resolution: {
      timestamp: new Date(Date.now() - 2 * 60000),
      verificationMethod: 'User login verification',
      success: true,
    },
  },
  {
    id: 'INC-002',
    title: 'Email sync errors on Outlook',
    description: 'Employee reports Outlook not syncing email. Messages are delayed by 2+ hours.',
    status: 'resolved',
    createdAt: new Date(Date.now() - 45 * 60000),
    updatedAt: new Date(Date.now() - 20 * 60000),
    priority: 'medium',
    category: 'Email',
    events: [
      {
        id: 'evt-7',
        timestamp: new Date(Date.now() - 45 * 60000),
        agent: 'triage',
        status: 'completed',
        message: 'Issue classified as Email Service problem. Priority: MEDIUM.',
      },
      {
        id: 'evt-8',
        timestamp: new Date(Date.now() - 40 * 60000),
        agent: 'investigation',
        status: 'completed',
        message: 'Investigation complete. Found KB article on Outlook sync issues.',
      },
      {
        id: 'evt-9',
        timestamp: new Date(Date.now() - 35 * 60000),
        agent: 'diagnosis',
        status: 'completed',
        message: 'Likely cause: Exchange cache corruption.',
      },
      {
        id: 'evt-10',
        timestamp: new Date(Date.now() - 30 * 60000),
        agent: 'action_planner',
        status: 'completed',
        message: 'Selected action: Clear Outlook cache.',
      },
      {
        id: 'evt-11',
        timestamp: new Date(Date.now() - 25 * 60000),
        agent: 'verification',
        status: 'completed',
        message: 'Action executed and verified. Email sync restored.',
      },
    ],
    evidence: [],
    approvalRequired: false,
    resolution: {
      timestamp: new Date(Date.now() - 20 * 60000),
      verificationMethod: 'Manual sync test',
      success: true,
    },
  },
  {
    id: 'INC-003',
    title: 'Suspicious login attempts detected',
    description: 'Security team detected multiple failed login attempts from unusual location.',
    status: 'escalated',
    createdAt: new Date(Date.now() - 60 * 60000),
    updatedAt: new Date(Date.now() - 55 * 60000),
    priority: 'critical',
    category: 'Security',
    events: [
      {
        id: 'evt-12',
        timestamp: new Date(Date.now() - 60 * 60000),
        agent: 'triage',
        status: 'completed',
        message: 'Issue classified as SECURITY incident. Priority: CRITICAL.',
      },
      {
        id: 'evt-13',
        timestamp: new Date(Date.now() - 58 * 60000),
        agent: 'investigation',
        status: 'completed',
        message: 'Investigation complete. Confirmed unusual login pattern.',
      },
      {
        id: 'evt-14',
        timestamp: new Date(Date.now() - 56 * 60000),
        agent: 'diagnosis',
        status: 'completed',
        message: 'RISK DETECTED: Potential security breach. Requires human review.',
      },
      {
        id: 'evt-15',
        timestamp: new Date(Date.now() - 55 * 60000),
        agent: 'action_planner',
        status: 'completed',
        message: 'Action: ESCALATE to Security team for manual investigation.',
      },
    ],
    evidence: [],
    approvalRequired: true,
    escalationReason: 'High-risk security incident requires human judgment and approval before action.',
  },
];

// Mock dashboard metrics
export const mockMetrics: DashboardMetrics = {
  activeIncidents: 2,
  aiResolutions: 24,
  escalations: 3,
  avgResolutionTime: 8,
};
